<main class="md-main">
    <section id="mb-main-content" class="md-main__content">
        <div class="mb-search-loading">
            <i class="iconfont icon-jishi-copy-copy"></i>
        </div>
        <h2 class="mb-search-wrap js-hidden"></h2>
        <div class="md-posts clearfix js-hidden"></div>
    </section>

    <aside class="md-main__sidebar">
        {% include '../common/sidebar.swig' %}
    </aside>
</main>